[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test"
script = "script"
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base_mainnet = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
